-- NOTE: This file is auto generated by ./sql-generator

-- AlbumUserMetadataRepository.upsert
insert into
  "album_user_metadata" ("albumId", "userId", "isFavorite")
values
  ($1, $2, $3)
on conflict ("albumId", "userId") do update
set
  "isFavorite" = "excluded"."isFavorite"
