-- NOTE: This file is auto generated by ./sql-generator

-- AlbumUserRepository.create
begin
insert into
  "album_user" ("userId", "albumId")
values
  ($1, $2)
returning
  "userId",
  "albumId",
  "role"
rollback

-- AlbumUserRepository.update
update "album_user"
set
  "role" = $1
where
  "userId" = $2
  and "albumId" = $3

-- AlbumUserRepository.delete
begin
delete from "album_user_metadata"
where
  "userId" = $1
  and "albumId" = $2
delete from "album_user"
where
  "userId" = $1
  and "albumId" = $2
commit
